import type { RegionPack } from "./types";

export const DEFAULT_SCORING = {
  min_score_to_keep: 35,
  title_weight: 30,
  skills_weight: 25,
  junior_boost: 15,
  mid_boost: 10,
  geo_boost: 20,
};

export const DEFAULT_RECENCY = {
  max_age_days: 14,
  reject_unknown_date: true,
  bucket_week_1_days: 7,
};

export const SENIORITY_CONFIG = {
  levels: ["intern", "junior", "mid", "senior", "lead", "executive"] as const,
  signals: {
    intern: ["intern", "internship", "apprentice", "trainee"],
    junior: [
      "junior",
      "jr.",
      "entry-level",
      "entry level",
      "fresher",
      "graduate",
      "new grad",
      "associate",
      "noc l1",
    ],
    mid: ["mid-level", "mid level", "intermediate", "noc l2"],
    senior: ["senior", "sr.", "staff", "principal"],
    lead: ["team lead", "tech lead", "engineering lead", "engineering manager", "manager"],
    executive: [
      "director",
      "head of",
      "vice president",
      "vp",
      "vp ",
      "vp,",
      "v.p",
      "chief",
      "cto",
      "cio",
      "ceo",
      "cfo",
      "coo",
      "executive",
      "general manager",
      "managing director",
    ],
  },
  max_job_level: {
    intern: "junior",
    junior_entry_associate: "junior",
    mid_or_unknown: "mid",
    senior: "senior",
    lead: "lead",
    executive: "executive",
  } as Record<string, string>,
  junior_hard_block_levels: ["senior", "lead", "executive"],
  credibility: {
    min_certs: 1,
    min_years: 2,
    min_skills: 5,
    project_keywords: [
      "project",
      "portfolio",
      "github",
      "built",
      "deployed",
      "contributed",
      "open source",
      "capstone",
    ],
  },
};

export const SKILL_SYNONYMS: Record<string, string[]> = {
  network: ["networking", "lan", "wan", "tcp/ip"],
  cisco: ["ccna", "ccnp", "ios"],
  noc: ["network operations", "network operations center"],
  firewall: ["palo alto", "fortinet", "checkpoint"],
  vpn: ["ipsec", "ssl vpn", "wireguard"],
  azure: ["microsoft azure", "az-104"],
  aws: ["amazon web services", "ec2"],
  linux: ["unix", "ubuntu", "rhel"],
  python: ["scripting", "automation"],
  troubleshooting: ["problem solving", "diagnostics"],
  "it support": ["helpdesk", "help desk", "service desk", "desktop support"],
  security: ["cybersecurity", "infosec"],
  cloud: ["saas", "iaas"],
  devops: ["ci/cd", "kubernetes"],
  data: ["analytics", "sql"],
  analyst: ["analysis"],
  javascript: ["js", "node.js", "nodejs"],
  typescript: ["ts"],
  react: ["react.js", "reactjs"],
};

export const REGIONS: RegionPack[] = [
  {
    id: "dubai",
    label: "Dubai / UAE",
    locations: ["Dubai", "UAE"],
    country_indeed: "uae",
    allow_signals: [
      "uae",
      "dubai",
      "abu dhabi",
      "sharjah",
      "gcc",
      "gulf",
      "saudi",
      "qatar",
      "bahrain",
      "kuwait",
      "oman",
      "middle east",
      "remote",
      "worldwide",
      "visa",
      "sponsor",
    ],
    reject_signals: [
      "united states only",
      "us citizen",
      "must be us based",
      "uk only",
      "eu only",
    ],
  },
  {
    id: "usa",
    label: "United States",
    locations: ["United States"],
    country_indeed: "usa",
    allow_signals: [
      "united states",
      "usa",
      "u.s.",
      "remote",
      "hybrid",
      "visa",
      "sponsor",
      "nationwide",
    ],
    reject_signals: [
      "india only",
      "uae only",
      "must be based in india",
      "gcc only",
    ],
  },
  {
    id: "india",
    label: "India",
    locations: ["India"],
    country_indeed: "india",
    allow_signals: [
      "india",
      "bangalore",
      "bengaluru",
      "hyderabad",
      "mumbai",
      "pune",
      "delhi",
      "noida",
      "gurgaon",
      "gurugram",
      "chennai",
      "lucknow",
      "remote",
      "hybrid",
    ],
    reject_signals: ["us citizen", "must be us based", "uae only", "gcc only"],
  },
  {
    id: "bangalore",
    label: "Bangalore / Bengaluru",
    locations: ["Bangalore", "Bengaluru", "India"],
    country_indeed: "india",
    allow_signals: [
      "bangalore",
      "bengaluru",
      "karnataka",
      "india",
      "remote",
      "hybrid",
    ],
    reject_signals: ["us citizen", "must be us based", "uae only"],
  },
  {
    id: "lucknow",
    label: "Lucknow",
    locations: ["Lucknow", "Uttar Pradesh", "India"],
    country_indeed: "india",
    allow_signals: [
      "lucknow",
      "uttar pradesh",
      "india",
      "remote",
      "hybrid",
      "noida",
      "delhi",
    ],
    reject_signals: ["us citizen", "must be us based", "uae only"],
  },
  {
    id: "alberta",
    label: "Alberta, Canada",
    locations: ["Alberta", "Canada"],
    country_indeed: "canada",
    allow_signals: [
      "alberta",
      "calgary",
      "edmonton",
      "canada",
      "remote",
      "hybrid",
      "visa",
    ],
    reject_signals: ["us citizen only", "india only", "uae only"],
  },
  {
    id: "washington",
    label: "Washington (US)",
    locations: ["Washington", "United States"],
    country_indeed: "usa",
    allow_signals: [
      "washington",
      "seattle",
      "bellevue",
      "redmond",
      "usa",
      "united states",
      "remote",
      "hybrid",
    ],
    reject_signals: ["india only", "uae only", "gcc only"],
  },
  {
    id: "warsaw",
    label: "Warsaw / Poland",
    locations: ["Warsaw", "Poland"],
    country_indeed: "poland",
    allow_signals: [
      "warsaw",
      "poland",
      "polska",
      "remote",
      "hybrid",
      "eu",
      "europe",
    ],
    reject_signals: ["us citizen only", "india only", "uae only"],
  },
  {
    id: "remote",
    label: "Remote / worldwide",
    locations: ["Remote", "Worldwide"],
    country_indeed: "usa",
    allow_signals: [
      "remote",
      "worldwide",
      "anywhere",
      "work from home",
      "wfh",
      "distributed",
    ],
    reject_signals: ["onsite only", "must relocate", "no remote"],
  },
  {
    id: "worldwide",
    label: "Worldwide",
    locations: ["Worldwide"],
    country_indeed: "usa",
    allow_signals: [
      "remote",
      "worldwide",
      "anywhere",
      "visa",
      "sponsor",
      "hybrid",
    ],
    reject_signals: [
      "us citizen only",
      "clearance required - citizens only",
    ],
  },
];

export function getRegion(id: string): RegionPack | undefined {
  return REGIONS.find((r) => r.id === id);
}
